[project]
name = "pgtkb"
version = "0.0.27"
description = "hello"
readme = "README.md"
authors = [
    { name = "tranngoctungchess-bit", email = "tranngoctung.chess@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pygame-ce >= 2.5.7"
]

[build-system]
requires = ["setuptools>=61.0", "cython>=3.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}