[project]
name = "pgtkb"
version = "0.0.26"
description = "hello"
readme = "README.md"
authors = [
    { name = "tranngoctungchess-bit", email = "tranngoctung.chess@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["uv_build>=0.10.10,<0.11.0"]
build-backend = "uv_build"