[project]
name = "PGTKernelBasic"
version = "0.23.8"
description = "hello"
readme = "README.md"
authors = [
    { name = "tranngoctungchess-bit", email = "tranngoctung.chess@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["Kernel*"]
exclude = ["tests*", "examples*"]