bg_widget = 1001
border = bg_widget + 1
corner_radius = border + 1
textpack = corner_radius + 1
Downrclick = textpack + 1
Downlclick = Downrclick + 1
Downscrollmouse = Downlclick + 1
Downscrollup = Downscrollmouse + 1
Downscrolldown = Downscrollup + 1
Uprclick = Downscrolldown + 1
Uplclick =  Uprclick + 1
Upscrollmouse = Uplclick + 1
Upscrollup = Upscrollmouse + 1
Upscrolldown = Upscrollup + 1
hover_bg = Upscrolldown + 1
pressed_bg = hover_bg + 1
Hoverfunc = pressed_bg + 1
Realeasefunc = Hoverfunc + 1
